### ISSUE TITLE
Added support for 1.16.5?

### ISSUE THREAD

**Issue by djcprone** [bonn2/unofficial-ssx-fabric-connector#1]
As the title suggests, is there any chance of support being added for 1.16.5 fabric servers? When I try to launch one such server with this mod installed, it goes into a restart loop as the mod looks for 1.17 version and fails.

**Comment by bonn2** [comment]
I no longer have a test environment set up for this mod, but I'll give it a look. If it is an easy port I'll get a release out with 1.16.5 support, otherwise I'm afraid I won't be able to help you as I personally no longer have use for this mod.

**Comment by djcprone** [comment]
> I no longer have a test environment set up for this mod, but I'll give it a look. If it is an easy port I'll get a release out with 1.16.5 support, otherwise I'm afraid I won't be able to help you as I personally no longer have use for this mod.

That would be awesome if you could. I'll donate to the cause if that helps or if you have a way for me to do so, to make it worth a little time for you, if you'd like. I'm just setting up a little network for my friends and I really want to get the ping info for my older server into my lobby. It's the missing piece :)

**Comment by bonn2** [comment]
Alright, so I've just done a test setup and discovered that this mod actually is unneeded (as far as I can tell).

You can gain all the functionality this mod provides by just turning on ping server (in the free version of SSX anyways)
![image](https://user-images.githubusercontent.com/42011672/141228241-013e8875-2f82-4eea-b67a-ce3d3c25fb55.png)

Then all you need is the fabric proxy mod from the README

I'll probably be archiving this repo in light of this.

Like I said I only used this mod for a few weeks, and never noticed that.

**Comment by djcprone** [comment]
> Alright, so I've just done a test setup and discovered that this mod actually is unneeded (as far as I can tell).
> 
> You can gain all the functionality this mod provides by just turning on ping server (in the free version of SSX anyways) ![image](https://user-images.githubusercontent.com/42011672/141228241-013e8875-2f82-4eea-b67a-ce3d3c25fb55.png)
> 
> Then all you need is the fabric proxy mod from the README
> 
> I'll probably be archiving this repo in light of this.
> 
> Like I said I only used this mod for a few weeks, and never noticed that.

Wow! Nice- I'm sorry that I didn't even try that. I do have the fabric proxy mod in there but I didn't even bother turning the ping on just because I figured this was required (since the original connector is required for the paper servers and such)

Thanks for looking into it and that's great to know!
